version: '3.9'
services:
  node-server:
    build: .
    container_name: introspect3-node-server-dev
    image: registry.cn-hangzhou.aliyuncs.com/timvel/introspect3-node-dev
    ports:
      - '3000:3000'
    restart: always
    env_file:
      - ./dev.env
    working_dir: /apps/node-server
    volumes:
      - ./src:/apps/node-server/src
    command: ['npm', 'run', 'start:dev']

    networks:
      timvel:
        aliases:
          - intro3-node-server

networks:
  timvel:
      name: timvel-network