name: build-and-push-docker-image

env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: 'registry.cn-hangzhou.aliyuncs.com/timvel/introspect3-node'

on:
  push:
    branches:
      - "master"
      - "releases/**"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          file: '{context}/Docker/Dockerfile'
